"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var punto_1 = require("./punto");
var p1 = new punto_1.Punto(3, 3);
var puntoAux = new punto_1.Punto(6, 7);
var puntoAux2 = new punto_1.Punto(6, 5);
var puntoAux3 = new punto_1.Punto(-6, -3);
var arrayPuntos = [puntoAux, puntoAux2, puntoAux3];
console.log(p1.toString());
console.log(p1.distanciaAlOrigen());
console.log(p1.calcularDistancia(puntoAux3));
console.log(p1.calcularCuadrante());
console.log(p1.calcularMasCercano(arrayPuntos));
