"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var punto_1 = require("./punto");
var triangulo_1 = require("./triangulo");
var p1 = new punto_1.Punto(3, 3);
var puntoAux = new punto_1.Punto(6, 7);
var puntoAux2 = new punto_1.Punto(6, 5);
var puntoAux3 = new punto_1.Punto(-6, -3);
var punto1 = new punto_1.Punto(0, 0);
var punto2 = new punto_1.Punto(0, 3);
var punto3 = new punto_1.Punto(3, 0);
var arrayPuntos = [puntoAux, puntoAux2, puntoAux3];
var t1 = new triangulo_1.Triangulo(punto1, punto2, punto3);
//console.log(p1.toString());
//console.log(p1.distanciaAlOrigen());
//console.log(p1.calcularDistancia(puntoAux));
//console.log(p1.calcularCuadrante());
console.log(p1.calcularMasCercano(arrayPuntos));
//console.log(t1.calcularLongitudLados());
//tsc -t es5 script.ts
